### ISSUE TITLE
Azure Looks Exactly Like Arc...

### ISSUE THREAD

**Issue by ghost** [vinceliuice/Azure-theme#6]
Hello,

Azure looks exactly like the Arc theme;

https://github.com/horst3180/arc-theme

Then someone took over the original Arc and forked it;

https://github.com/NicoHood/arc-theme

So if you're going to use someone's theme give credit were credit is due...

I find it very unlikely you created this from scratch and it turned out just like Arc...

Hmm

**Comment by vinceliuice** [comment]
Azure is based on arc theme.

**Comment by Geyup** [comment]
Ok, where do you mention this?

Because even though it's a theme Arc is listed under the GPL and you have to mention this somewhere;

https://github.com/horst3180/arc-theme/blob/master/COPYING

By the way, not trying to be mean, or rude here, just stating facts of using someone else's work...

Cheers

**Comment by ghost** [comment]
Sorry I see you mentioned this in the AUTHORS... My bad...

Since NicoHood forked it, I don't see anything different between your versions and his...

Hmm

If you could put this out for GTK 3.18 that would be appreciated...

Thanks

**Comment by vinceliuice** [comment]
Perhaps added in the author file is not obvious enough, I add this to the README now!
